name: Build Flutter Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3' # 用已发布的稳定版
        cache: true

    - name: Install dependencies
      run: |
        flutter config --no-analytics
        flutter pub upgrade --major-versions # 强制升级依赖版本
        flutter pub get

    - name: Build release APK
      run: flutter build apk --release --split-per-abi

    - name: Upload compiled APK
      uses: actions/upload-artifact@v4
      with:
        name: Selene-Release-APK
        path: build/app/outputs/flutter-apk/
